version: '3.7'

services: 
    webapp-server:
        build:
            context: .
            dockerfile: Dockerfile
        image: assoy-server-img
        container_name: assoy-express
        volumes: 
            - .:/gambar
        ports: 
            - "6900:6900"
        env_file: .env
        environment: 
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_DB=$MONGO_DB
            - MONGO_USN=$MONGO_USN
            - MONGO_PASS=$MONGO_PASS